#!/bin/bash
clear

echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[41;1;37m                        ⇱ MENU VPS ⇲                    \E[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e ""
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━【SSH WS SSL】━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[0;34m* add-ssh\e[0m       : Create SSH Websocket SSL Account"
echo -e "\033[0;34m* trial-ssh\e[0m     : Create SSH Websocket SSL Trial Account"
echo -e "\033[0;34m* renew\e[0m         : Extending SSH Websocket SSL Account Active Life"
echo -e "\033[0;34m* hapus\e[0m         : Delete SSH Websocket SSL"
echo -e "\033[0;34m* cek\e[0m           : Check User Login SSH Websocket SSL"
echo -e "\033[0;34m* member\e[0m        : List Member SSH Websocket SSL"
echo -e "\033[0;34m* autokill\e[0m      : Set up Autokill SSH Websocket SSL"
echo -e "\033[0;34m* ceklim\e[0m        : Displays Users Who Do Multi Login SSH Websocket SSL"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e ""
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━【XRAY/VMESS_TLS】━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[0;34m* add-vmess\e[0m     : Create XRAY Vmess TLS Websocket Account"
echo -e "\033[0;34m* del-user\e[0m      : Deleting XRAY Vmess TLS Websocket Account"
echo -e "\033[0;34m* renew-user\e[0m    : Extending XRAY Vmess TLS Account Active Life"
echo -e "\033[0;34m* monitor\e[0m       : Check User Login XRAY Vmess TLS"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e ""
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━【XRAY/VLESS_XTLS】━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[0;34m* add-vlessxtls\e[0m : Create XRAY Vless XTLS Websocket Account"
echo -e "\033[0;34m* del-user\e[0m      : Deleting XRAY Vless XTLS Websocket Account"
echo -e "\033[0;34m* renew-user\e[0m    : Extending XRAY Vless XTLS Active Life"
echo -e "\033[0;34m* monitor\e[0m       : Check User Login XRAY Vless XTLS"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e ""
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━【XRAY/TROJAN_TCP】━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[0;34m* add-trojan\e[0m    : Create XRAY Trojan TCP Account"
echo -e "\033[0;34m* del-user\e[0m      : Deleting XRAY Trojan TCP Account"
echo -e "\033[0;34m* renew-user\e[0m    : Extending XRAY Trojan TCP Active Life"
echo -e "\033[0;34m* monitor\e[0m       : Check User Login XRAY Trojan TCP"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e ""
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━【OTHER】━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[0;34m* autobackup\e[0m    : Autobackup Data VPS"
echo -e "\033[0;34m* autoreboot\e[0m    : Autoreboot VPS"
echo -e "\033[0;34m* backup\e[0m        : Backup Data VPS"
echo -e "\033[0;34m* del-exp\e[0m        : Autodelete Expired Account (ssh,vmess,vless,trojan)"
echo -e "\033[0;34m* tcp-tweaker\e[0m   : Tweak Tcp"
echo -e "\033[0;34m* htop\e[0m          : Monitoring Cpu Usage"
echo -e "\033[0;34m* limit-speed\e[0m   : Limit Bandwith Speed Server"
echo -e "\033[0;34m* pointing-vps\e[0m  : Pointing VPS"
echo -e "\033[0;34m* ram\e[0m           : Check Usage of VPS Ram"
echo -e "\033[0;34m* reboot\e[0m        : Reboot VPS"
echo -e "\033[0;34m* restore\e[0m       : Restore Data VPS"
echo -e "\033[0;34m* restart\e[0m       : Restart Service Dropbear, Squid, OpenVPN dan SSH"
echo -e "\033[0;34m* speedtest\e[0m     : Speedtest VPS"
echo -e "\033[0;34m* wbmn\e[0m          : Install Webmin"
echo -e "\033[0;34m* update-kernel\e[0m : Update Kernel VPS To Latest Version"
echo -e "\033[0;34m* menu2\e[0m         : Back To Homepage"
echo -e "\033[0;34m* info\e[0m          : Displaying System Information"
echo -e "\033[0;34m* exit\e[0m          : Exit From VPS"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
